# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title gdata
#' @name gdata
#' @description A function that generates parameters of source models and target model 
#' @param h Measure the degree of similarity between the source model and the target model parameters in set A
#' @param p Parameter dimension
#' @param s The number of non-zero elements in the parameter
#' @param M The number of source models
#' @param sigbeta One of the initialization values of the parameter
#' @param key 1 or 2 represents different data settings
#' @param sizeA0 Number of source models in set A
#' @param nk The sample size of source models
#' @return B Generated parameters of target model and source models 
#' @examples
#' \dontrun{
#' h=2; p=20; s=11; M=10; sigbeta=0.4; key=1;  sizeA0=4; nk=50
#' B <- gdata(h,p,s,M,sigbeta,key,sizeA0,nk)
#' }
#' @export
gdata <- function(h, p, s, M, sigbeta, key, sizeA0, nk) {
    .Call('_SA23204163_gdata', PACKAGE = 'SA23204163', h, p, s, M, sigbeta, key, sizeA0, nk)
}

